from setuptools import setup
APP = ['my ACTUAL game.py']
DATA_FILES = ['backroundsound.mp3',
'Boom00.png',
'Boom01.png',
'Boom02.png',
'Boom03.png',
'Boom04.png',
'Boom05.png','Boom06.png',
'Boom07.png',
'Boom08.png',
'coin.png',
'deathsound.mp3',
'expl00.png',
'expl01.png',
'expl02.png',
'expl03.png',
'expl04.png',
'expl05.png',
'expl06.png',
'expl07.png',
'expl08.png',
'heart.png',
'Lazer.wav',
'light.png',
'middle.png',
'mushroom.png',
'mushroom1.png',
'mushroom2.png',
'my ACTUAL game.py',
'My_face.png',
'pop.wav',
'pop2.wav',
'powerup.wav',
'screen.png',
'shield.png']
OPTIONS = {'argv_emulation': True}
 
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)